### ISSUE TITLE
Goblin Blastmage gets played before the bot plays a Mech

### ISSUE THREAD

**Issue by davidmann4** [noHero123/silverfish#10] opened 2015-08-25 19:12 UTC
The Bot seems to play the Mechmage before mechs in the same turn.

maybe he does not understand the card correctly?

card silverfish code: ( Sim_GvG_004.cs ) 
https://github.com/noHero123/silverfish/blob/2f7606c8d8e2a77f9878e300c8e77b30c989cc4a/cards/Sim_GvG_004.cs

![image](https://cloud.githubusercontent.com/assets/1736570/9476498/4e979c06-4b6d-11e5-9573-bd10e32f48cb.png)

**Comment by D-Nice** [comment] 2015-08-25 20:14
https://github.com/noHero123/silverfish/pull/11

This change should ensure it is played correctly, if the methods in it are correct. I can't test it as I don't own a Goblin Blastmage :(.

**Comment by davidmann4** [comment] 2015-08-25 21:01
I can compile and test it - just tell me when you have it ready!

**Comment by D-Nice** [comment] 2015-08-25 21:39
Try compiling this one: https://github.com/D-Nice/silverfish

You can also just take the PenalityManager.cs and Program.cs and apply it to NoHero's

**Comment by yann510** [comment] 2015-08-26 13:58
Here I have almost the same problem, but with another card, the flametongue totem is being played after the bot has attacked with the minions.

**Comment by davidmann4** [comment] 2015-08-26 16:26
@D-Nice hmm was not able to build your version - can you provide me a .dll and a list of stuff to test?

I guess:
*Golblin Blast Mage
*flametongue totem

**Comment by D-Nice** [comment] 2015-08-27 17:13
You can simply copy and paste over the PenalityManager.cs from my forked repo, over NoHero's, and compile then, if you aren't able to compile the whole package, to test it out.

**Comment by D-Nice** [comment] 2015-08-27 17:15
The biggest issue really is, how high you have your maxwide, if you have your maxwide as high as possible, it will always do the absolute best, the issue is, the more complex the board becomes, it can start taking several seconds, to even minutes, to fully find out the best move. Hence, the best course of action would be code optimization, or doing several complex board tests, with different maxwide and other ai variables, and seeing which is fast enough to use, and chooses the correct move every time.

**Comment by D-Nice** [comment] 2015-08-28 18:25
Have you tried it with goblin blastmage yet?

**Comment by davidmann4** [comment] 2015-08-28 20:05
no - let me try to compile and test it now

**Comment by davidmann4** [comment] 2015-08-28 20:16
can not build it - code to messy for me sorry

**Comment by noHero123** [comment] 2015-09-01 09:13
will be fixed next version

**Closed by noHero123** 2015-09-01 09:13 UTC

**Comment by davidmann4** [comment] 2015-09-01 13:48
very cool - if you put out a release ( https://github.com/noHero123/silverfish/releases ) I can test it for you!
